### ISSUE TITLE
ToDo List for Moby Simulator

### ISSUE THREAD

**Issue by 00h-i-r-a00** [00h-i-r-a00/moby_simulator#1]
- [x] naming of the results file to reflect the configuration
- [x] how to incorporate seeds (+ seed iterations), queue sizes (and later trust scores) in the configurations
- [x] automation of the workflow - break it down into subtasks
- [x] automation of the graph producing workflow - break it down into subtasks
- [x] automation of the epidemic routing workflow for queue sizes 
- [x] measure message drops over time
- [ ] find connectivity of the graph
- [x] Investigate the dip in the New Delivery Ratios.
- [x] Check delivery ratio in terms of 1. users that leave each hour 2. active number of "new" users every hour, and 3. whether there are less number of users "per tower" (would make for a fewer message exchanges) - Alternatively for (3) the distribution of the number of users per hour per tower (a boxplot would be nice)
- [ ] Average Delay Latency to compute cooldown
- [X] Plot the Active number of users against different timezones: 1. GMT 2. Local Spain Time
- [ ] (optional) Move seed file's configuration section from text to JSON.

**Comment by amoghbl1** [comment]
I feel this might be outdated. We need to update it.

**Comment by 00h-i-r-a00** [comment]
Yeah, it would be nice to have it here rather than the doc.

**Comment by amoghbl1** [comment]
Tracking tasks using other means. Don't need this anymore.
